### ISSUE TITLE
Sonarr season support

### ISSUE THREAD

**Issue by m-bernard** [ngovil21/PlexRequestChannel.bundle#10] opened 2016-02-07 03:34 UTC
When using Sonarr, it would be nice if users could request specific seasons instead of having to use the same global default for all series.

**Comment by ngovil21** [comment] 2016-02-07 20:23
I'll think about this, but it's not going flow well with the Plex interface.

**Comment by ngovil21** [comment] 2016-02-11 07:19
@pax0707
I added the ability to manage shows in sonarr from inside the channel. For the admin, or users that are allowed to manage sonarr, which can be added from Manage User, they can trigger Sonarr to search for all episodes in a series, season, or individual episode.

Also in View Request, if a show already exists in Sonarr, then Send To Sonarr will bring up the menu to search for seasons or episodes regardless of the setting in manage user. Non-admin users will need to have to have the view request setting enabled to see the requests menu.

This kind of makes it a two step process (add show to sonarr, then manage show), but it also gives you the ability to go back afterwards and search for more episodes when you need to.

This is currently in the development branch if you would like to test it out.

**Comment by pax0707** [comment] 2016-02-11 18:39
And what if we don't use sonarr?
;- )=

**Comment by ngovil21** [comment] 2016-02-11 18:49
Sorry my mistake, I thought you were looking at Sonarr too. I haven't been able to test SickRage, my installation wouldn't work, but I've confirmed that SickBeard does work. I'll work on other clients, but it'll be much harder because I won't be able to test it directly. I'll give it another shot this weekend.

**Comment by ngovil21** [comment] 2016-02-25 23:14
@m-bernard So I this has implemented by setting the Sonarr  `Monitor Seasons` preference to manual. This setting will add the show to Sonarr and then redirect the user to manage the added show. Might not be the smoothest, but it gives a lot of flexibility in how you want to manage the show, choose seasons or individual episodes. I know you had started on a fork, just another option. Let me know if you have a pull request that you thinks improves anything.

@pax0707 This feature is also been implemented using Sickbeard/SickRage.

Sorry this is late, just seeing if I can close the issue.

**Comment by camjac251** [comment] 2016-02-27 03:06
I had this idea for lokenx's plexrequests but was told that he didn't want to add it in. 
But the idea was that when you click add on a TV show it'll popup with a box asking you what episode you last watched with the options of all the episodes and the one defaulting to "I haven't watched any". If that's selected then it would add all of the episodes and auto search for them, if they select a specific episode, it would deselect the episodes monitored status (I use Sonarr) all up to the episode they selected.

**Comment by ngovil21** [comment] 2016-02-27 16:59
@camjac251 Well that's kind of specific, but the way the channel works is that if you request a new show that isn't in Sonarr, then the show will be added according to the Preference `Monitor Seasons`. If this is set to 'manual', then when sending to Sonarr, you will be given a menu of the specific seasons/episodes you would like to download.

If a show already exists in Sonarr, then the menu to chose seasons/episodes to downloads is shown for you to make changes. It doesn't keep track of watched status, but seasons/episodes that are already monitored will be shown with a * in front of them.

**Closed** 2016-03-01 20:02 UTC
